### ISSUE TITLE
In class feedback

### ISSUE THREAD

**Issue by dmartss** [Asher978/App_On_My_Feet#1]
Great project - I'm very impressed with all of the functionality, especially implementing the different sources to get information from and apply it to the users experience and interaction. Also impressed with the creativity of using a lot of different features we didn't learn in class.

Improvements for the future we discussed:

1.  Adding a ranking board for the different runners - to compare everyones progress in reaching the 500 mile goal mark. 

2. Adding to the commenting functionality, its awesome as it is right now, but displaying users names when they comment on other peoples runs would be even cooler.
 
3. The mobile site looks great, but adding full functionality to it. 

Overall amazing job!

**Comment by Asher978** [comment]
Hey Dan, 
Thanks for taking the time to browse through my project. It was great hearing your feedback as most of it is what I want to implement. 

`Adding a ranking board for the different runners - to compare everyones progress in reaching the 500 mile goal mark.`
  *  Totally agree. I need to create a ranking page. I think this will be a great addition as it will allow and enable every user to view the entire team's progress in one page. I already started on this page and once completed will push the update. I will let you know so you can view the changes. 

 `Adding to the commenting functionality, its awesome as it is right now, but displaying users names when they comment on other peoples runs would be even cooler.`
  *  I need to create a query that returns the users name and comments together... probably a JOIN will work in this situation. After the ranking page this will be tackled. 

`The mobile site looks great, but adding full functionality to it.`
  *  Few drop down buttons are not fully functional in the mobile views. I need to work at the bootstrap templates to achieve it.

Want to thank you for your feedback. Will let you know once the changes are implemented.

Ash
